language: go
go:
  - "1.9"
  - "1.10"
install:
  - make dependencies
script:
  - make test
notifications:
  email: false
  slack:
    rooms:
      - secure: "JE0qzKsOrCV2M2EvDWubkKcYpQ3LJnk560kiNgvF39wAuTx/giddIbnYO6zsmZ3uhtdcSnIzg8gH+kHuFuVgGMvAaoAXqh6fOzwtUW88Z4IWsrv+6RDNXnbQHdT3+Ga3X7J7THKYe4yaqcB6wMjZy2JHQdNdhoPKoz2qrCf9pXywVOSRLwDW0/bWsyy2+DuoxJ1MUzyVLYhhxuZ6kB0tUXoWMB3GvpDF561TdSCrm7EcV0TkzkMk9703vlzjrDMo8YSgeo2eTikje6CMSozHX/bSzDPuUf+quEvID4PrzO7WuD+sRWYqyswpjxyLrl54lO1LxUe+pDW6QLoIaJxAmyvOViN4yX7kfIjOsveTgLv4O7XT2IVbgnSazdEfhMpJiQMdWJrdyS8sJHI37l2lMk/x6G5plLe8fERhdGSrUEmIRVwUSap9YtjfllUH/ZaWzlSOl6c/HPXfInjlE6Qexwj6odsfhCGsYCNkhXATfwe+5D1TBR17TzFvy4JZLcWPtyo5U5XXtMSMZ9/7P33fGbrobvKdX8y2q2fD6lE7Ozp8+jEnxYJZffgbeSq7ogog/Niqv1JLLLJKzopPBEdXjTsSRquUNPrKQtUvKvuy1uPq0l7RWCl86Tm1B/53hJnMDyT/PmcL0+cOtVTzeM6e0TZ3RgYRPE51k+GSeVZp5kY="
    on_success: always
    on_failure: always

